package it.trenical.server.gui;

import it.trenical.common.Route;
import it.trenical.common.Train;
import it.trenical.common.Trip;

import javax.swing.*;
import javax.swing.border.TitledBorder;

import java.awt.*;
import java.text.SimpleDateFormat;

import static it.trenical.common.gui.Util.formatLabel;

public class DeleteTripDialog extends DeleteDialog<Trip> {

    private JPanel main;
    private JLabel trainLabel;
    private JLabel dateLabel;
    private JLabel economySeatsLabel;
    private JLabel routeLabel;
    private JLabel businessSeatsLabel;

    static private final SimpleDateFormat dateFormatter = new SimpleDateFormat("dd/MM/yyyy HH:mm");

    public DeleteTripDialog(Trip item) {
        super(item);
        addToInfoPane(main);

        Route r = item.getRoute();
        Train tr = item.getTrain();
        formatLabel(trainLabel, tr.getId(), tr.getType().getName());
        formatLabel(dateLabel, dateFormatter.format(item.getDepartureTime().getTime()));
        formatLabel(routeLabel, r.getDepartureStation().getTown(), r.getArrivalStation().getTown());
        formatLabel(economySeatsLabel, item.getAvailableEconomySeats());
        formatLabel(businessSeatsLabel, item.getAvailableBusinessSeats());
    }

    @Override
    void deleteItem() {
        server.deleteTrip(itemToDelete);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        main = new JPanel();
        main.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), -1, -1));
        main.setBorder(BorderFactory.createTitledBorder(null, "Viaggio", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION, null, null));
        trainLabel = new JLabel();
        trainLabel.setText("Treno: %d - %s");
        main.add(trainLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        economySeatsLabel = new JLabel();
        economySeatsLabel.setText("Posti Economy disponibili: %s");
        main.add(economySeatsLabel, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        businessSeatsLabel = new JLabel();
        businessSeatsLabel.setText("Posti Business disponibili: %s");
        main.add(businessSeatsLabel, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        routeLabel = new JLabel();
        routeLabel.setText("Tratta: da %s a %s");
        main.add(routeLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        dateLabel = new JLabel();
        dateLabel.setText("Data partenza: %s");
        main.add(dateLabel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return main;
    }
}
