package it.trenical.server.gui;

import it.trenical.common.Train;

import javax.swing.*;
import javax.swing.border.TitledBorder;

import java.awt.*;

import static it.trenical.common.gui.Util.formatLabel;

public class DeleteTrainDialog extends DeleteDialog<Train> {

    private JPanel main;
    private JLabel idLabel;
    private JLabel typeLabel;
    private JLabel economyCapLabel;
    private JLabel businessCapLabel;

    public DeleteTrainDialog(Train item) {
        super(item);
        addToInfoPane(main);
        formatLabel(idLabel, item.getId());
        formatLabel(typeLabel, item.getType().getName());
        formatLabel(economyCapLabel, item.getEconomyCapacity());
        formatLabel(businessCapLabel, item.getBusinessCapacity());

    }

    @Override
    void deleteItem() {
        server.deleteTrain(itemToDelete);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        main = new JPanel();
        main.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        main.setBorder(BorderFactory.createTitledBorder(null, "Treno", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION, null, null));
        idLabel = new JLabel();
        idLabel.setText("ID: %s");
        main.add(idLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        typeLabel = new JLabel();
        typeLabel.setText("Tipo: %s");
        main.add(typeLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        economyCapLabel = new JLabel();
        economyCapLabel.setText("Capacità Economy: %d");
        main.add(economyCapLabel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        businessCapLabel = new JLabel();
        businessCapLabel.setText("Capacità Business: %d\n");
        main.add(businessCapLabel, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return main;
    }
}
