package it.trenical.server.gui;

import it.trenical.common.Promotion;

import javax.swing.*;
import javax.swing.border.TitledBorder;

import java.awt.*;

import static it.trenical.common.gui.Util.formatLabel;

public class DeletePromotionDialog extends DeleteDialog<Promotion> {

    private JPanel main;
    private JLabel nameLabel;
    private JLabel codeLabel;
    private JLabel descriptionLabel;
    private JLabel discountLabel;
    private JLabel onlyFidelityLabel;

    public DeletePromotionDialog(Promotion item) {
        super(item);
        addToInfoPane(main);
        formatLabel(codeLabel, item.getCode());
        formatLabel(nameLabel, item.getName());
        formatLabel(descriptionLabel, item.getDescription());
        formatLabel(discountLabel, convertDiscount(item.getDiscount()));
        formatLabel(onlyFidelityLabel, item.isOnlyFidelityUser() ? "Si" : "No");
    }

    private int convertDiscount(float x) {
        return (int) (1 - x) * 100;
    }

    @Override
    void deleteItem() {
        server.deletePromotion(itemToDelete);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        main = new JPanel();
        main.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), -1, -1));
        main.setBorder(BorderFactory.createTitledBorder(null, "Promozione", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION, null, null));
        nameLabel = new JLabel();
        nameLabel.setText("Nome: %s");
        main.add(nameLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        descriptionLabel = new JLabel();
        descriptionLabel.setText("Descrizione: %s");
        main.add(descriptionLabel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        discountLabel = new JLabel();
        discountLabel.setText("Sconto: %d perc.");
        main.add(discountLabel, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        codeLabel = new JLabel();
        codeLabel.setText("Codice: %s");
        main.add(codeLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        onlyFidelityLabel = new JLabel();
        onlyFidelityLabel.setText("Solo per fedeli: %s");
        main.add(onlyFidelityLabel, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return main;
    }
}
