package it.trenical.server.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import it.trenical.common.Station;

import javax.swing.*;
import javax.swing.border.TitledBorder;

import java.awt.*;

import static it.trenical.common.gui.Util.formatLabel;

public class DeleteStationDialog extends DeleteDialog<Station> {

    private JPanel main;
    private JLabel nameLabel;
    private JLabel addressLabel;
    private JLabel townLabel;
    private JLabel provinceLabel;

    public DeleteStationDialog(Station item) {
        super(item);
        addToInfoPane(main);
        formatLabel(nameLabel, item.getName());
        formatLabel(addressLabel, item.getAddress());
        formatLabel(townLabel, item.getTown());
        formatLabel(provinceLabel, item.getProvince());
    }

    @Override
    void deleteItem() {
        server.deleteStation(itemToDelete);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        main = new JPanel();
        main.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        main.setBorder(BorderFactory.createTitledBorder(null, "Stazione", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION, null, null));
        nameLabel = new JLabel();
        nameLabel.setText("Nome: %s");
        main.add(nameLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        addressLabel = new JLabel();
        addressLabel.setText("Indirizzo: %s");
        main.add(addressLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        provinceLabel = new JLabel();
        provinceLabel.setText("Provincia: %s");
        main.add(provinceLabel, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        townLabel = new JLabel();
        townLabel.setText("Città: %s");
        main.add(townLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return main;
    }

}
