package it.trenical.server.gui;

import it.trenical.common.TrainType;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class DeleteTrainTypeDialog extends DeleteDialog<TrainType> {

    private JPanel main;
    private JLabel nameLabel;
    private JLabel priceLabel;

    public DeleteTrainTypeDialog(TrainType item) {
        super(item);
        addToInfoPane(main);
        nameLabel.setText(String.format(nameLabel.getText(), item.getName()));
        priceLabel.setText(String.format(priceLabel.getText(), item.getPrice()));
    }

    @Override
    void deleteItem() {
        server.deleteTrainType(itemToDelete);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        main = new JPanel();
        main.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        main.setBorder(BorderFactory.createTitledBorder(null, "Tipo di Treno", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION, null, null));
        nameLabel = new JLabel();
        nameLabel.setText("Nome: %s");
        main.add(nameLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        priceLabel = new JLabel();
        priceLabel.setText("Prezzo: %s");
        main.add(priceLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return main;
    }
}
