package it.trenical.server.gui;

import it.trenical.common.Route;

import javax.swing.*;
import javax.swing.border.TitledBorder;

import java.awt.*;

import static it.trenical.common.gui.Util.formatLabel;

public class DeleteRouteDialog extends DeleteDialog<Route> {

    private JPanel main;
    private JLabel departureLabel;
    private JLabel arrivalLabel;
    private JLabel distanceLabel;

    public DeleteRouteDialog(Route item) {
        super(item);
        addToInfoPane(main);
        formatLabel(departureLabel, item.getDepartureStation().getTown());
        formatLabel(arrivalLabel, item.getDepartureStation().getTown());
        formatLabel(distanceLabel, item.getDistance());

    }

    @Override
    void deleteItem() {
        server.deleteRoute(itemToDelete);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        main = new JPanel();
        main.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        main.setBorder(BorderFactory.createTitledBorder(null, "Tratta", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION, null, null));
        departureLabel = new JLabel();
        departureLabel.setText("Stazione di partenza: %s");
        main.add(departureLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        arrivalLabel = new JLabel();
        arrivalLabel.setText("Stazione di arrivo: %s");
        main.add(arrivalLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        distanceLabel = new JLabel();
        distanceLabel.setText("Distanza tra stazioni: %d");
        main.add(distanceLabel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return main;
    }
}
